[package]
name = "api_models"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
license.workspace = true

[dependencies]
actix-web = { version = "4.9.0", optional = true}
